name: Test
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: xzfc
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - name: Install and test cached-nix-shell
      run: nix-env -i -f default.nix && ./tests/run.sh
    - name: Test nix-trace
      run: nix-shell ./default.nix --run 'make -C ./nix-trace test'
